services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
    ports:
      - 3306:3306
    volumes:
      - ./Database/data:/var/lib/mysql
  middleware:
    build: ./Middleware
    image: mysql/mysql-server
    command: npm run prod
    volumes:
      - ./Middleware:/src
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    restart: always
  microservice_accounts_1:
    build: ./Microservices/Accounts
    command: npm run prod
    volumes:
      - ./Microservices/Accounts:/app
    ports:
      - "5001:5000"
    restart: always
  microservice_accounts_2:
    build: ./Microservices/Accounts
    command: npm run prod
    volumes:
      - ./Microservices/Accounts:/app
    ports:
      - "5002:5000"
    restart: always
  application:
    build: ./Application
    command: npm start
    volumes:
      - ./Application:/app
    ports:
      - "3000:3000"
  nginx:
    build: ./Proxy
    depends_on:
      - microservice_accounts_1
      - microservice_accounts_2
    ports:
      - "5100:5100"
    restart: always