services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
    ports:
      - 3306:3306
    volumes:
      - ./Database/data:/var/lib/mysql
  middleware:
    build: ./Middleware
    image: mysql/mysql-server
    command: npm run prod
    volumes:
      - ./Middleware:/src
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    # restart: always
  microservice_accounts:
    build: ./Microservices/Accounts
    command: npm run prod
    volumes:
      - ./Microservices/Accounts:/app
    ports:
      - "5000:5000"
    restart: always
  application:
    build: ./Application
    # command: npm start
    command: npm run dev
    volumes:
      - ./Application:/app
    ports:
      - "3000:3000"
      # - "8080:8080"
  nginx:
    build: ./Proxy
    depends_on:
      - microservice_accounts
    ports:
      - "5100:5100"
    restart: always